# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import database_service_pb2 as database__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in database_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DatabaseManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTableNames = channel.unary_unary(
                '/databasemanagement.DatabaseManagementService/ListTableNames',
                request_serializer=database__service__pb2.ListTablesRequest.SerializeToString,
                response_deserializer=database__service__pb2.TableNamesResponse.FromString,
                _registered_method=True)
        self.DropAllTables = channel.unary_unary(
                '/databasemanagement.DatabaseManagementService/DropAllTables',
                request_serializer=database__service__pb2.DropAllTablesRequest.SerializeToString,
                response_deserializer=database__service__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.CreateAllTables = channel.unary_unary(
                '/databasemanagement.DatabaseManagementService/CreateAllTables',
                request_serializer=database__service__pb2.CreateAllTablesRequest.SerializeToString,
                response_deserializer=database__service__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.PrintTable = channel.unary_unary(
                '/databasemanagement.DatabaseManagementService/PrintTable',
                request_serializer=database__service__pb2.StringCommandRequest.SerializeToString,
                response_deserializer=database__service__pb2.TableContentResponse.FromString,
                _registered_method=True)
        self.ExecuteSql = channel.unary_unary(
                '/databasemanagement.DatabaseManagementService/ExecuteSql',
                request_serializer=database__service__pb2.StringCommandRequest.SerializeToString,
                response_deserializer=database__service__pb2.OperationResponse.FromString,
                _registered_method=True)


class DatabaseManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTableNames(self, request, context):
        """Print the contents of a specific table
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropAllTables(self, request, context):
        """Drop all tables in the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAllTables(self, request, context):
        """Create all tables in the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintTable(self, request, context):
        """Print a table in the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSql(self, request, context):
        """Execute raw sql into the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTableNames': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTableNames,
                    request_deserializer=database__service__pb2.ListTablesRequest.FromString,
                    response_serializer=database__service__pb2.TableNamesResponse.SerializeToString,
            ),
            'DropAllTables': grpc.unary_unary_rpc_method_handler(
                    servicer.DropAllTables,
                    request_deserializer=database__service__pb2.DropAllTablesRequest.FromString,
                    response_serializer=database__service__pb2.OperationResponse.SerializeToString,
            ),
            'CreateAllTables': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAllTables,
                    request_deserializer=database__service__pb2.CreateAllTablesRequest.FromString,
                    response_serializer=database__service__pb2.OperationResponse.SerializeToString,
            ),
            'PrintTable': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintTable,
                    request_deserializer=database__service__pb2.StringCommandRequest.FromString,
                    response_serializer=database__service__pb2.TableContentResponse.SerializeToString,
            ),
            'ExecuteSql': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSql,
                    request_deserializer=database__service__pb2.StringCommandRequest.FromString,
                    response_serializer=database__service__pb2.OperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'databasemanagement.DatabaseManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('databasemanagement.DatabaseManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTableNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/databasemanagement.DatabaseManagementService/ListTableNames',
            database__service__pb2.ListTablesRequest.SerializeToString,
            database__service__pb2.TableNamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropAllTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/databasemanagement.DatabaseManagementService/DropAllTables',
            database__service__pb2.DropAllTablesRequest.SerializeToString,
            database__service__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAllTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/databasemanagement.DatabaseManagementService/CreateAllTables',
            database__service__pb2.CreateAllTablesRequest.SerializeToString,
            database__service__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/databasemanagement.DatabaseManagementService/PrintTable',
            database__service__pb2.StringCommandRequest.SerializeToString,
            database__service__pb2.TableContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSql(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/databasemanagement.DatabaseManagementService/ExecuteSql',
            database__service__pb2.StringCommandRequest.SerializeToString,
            database__service__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
