# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'database_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x61tabase_service.proto\x12\x12\x64\x61tabasemanagement\"\x13\n\x11ListTablesRequest\"\x16\n\x14\x44ropAllTablesRequest\"\x18\n\x16\x43reateAllTablesRequest\"\'\n\x14StringCommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\":\n\x12TableNamesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0btable_names\x18\x02 \x03(\t\"5\n\x11OperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x14TableContentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\ntable_rows\x18\x02 \x03(\t2\x8f\x04\n\x19\x44\x61tabaseManagementService\x12\x61\n\x0eListTableNames\x12%.databasemanagement.ListTablesRequest\x1a&.databasemanagement.TableNamesResponse\"\x00\x12\x62\n\rDropAllTables\x12(.databasemanagement.DropAllTablesRequest\x1a%.databasemanagement.OperationResponse\"\x00\x12\x66\n\x0f\x43reateAllTables\x12*.databasemanagement.CreateAllTablesRequest\x1a%.databasemanagement.OperationResponse\"\x00\x12\x62\n\nPrintTable\x12(.databasemanagement.StringCommandRequest\x1a(.databasemanagement.TableContentResponse\"\x00\x12_\n\nExecuteSql\x12(.databasemanagement.StringCommandRequest\x1a%.databasemanagement.OperationResponse\"\x00\x42\x08Z\x06/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006/proto'
  _globals['_LISTTABLESREQUEST']._serialized_start=46
  _globals['_LISTTABLESREQUEST']._serialized_end=65
  _globals['_DROPALLTABLESREQUEST']._serialized_start=67
  _globals['_DROPALLTABLESREQUEST']._serialized_end=89
  _globals['_CREATEALLTABLESREQUEST']._serialized_start=91
  _globals['_CREATEALLTABLESREQUEST']._serialized_end=115
  _globals['_STRINGCOMMANDREQUEST']._serialized_start=117
  _globals['_STRINGCOMMANDREQUEST']._serialized_end=156
  _globals['_TABLENAMESRESPONSE']._serialized_start=158
  _globals['_TABLENAMESRESPONSE']._serialized_end=216
  _globals['_OPERATIONRESPONSE']._serialized_start=218
  _globals['_OPERATIONRESPONSE']._serialized_end=271
  _globals['_TABLECONTENTRESPONSE']._serialized_start=273
  _globals['_TABLECONTENTRESPONSE']._serialized_end=332
  _globals['_DATABASEMANAGEMENTSERVICE']._serialized_start=335
  _globals['_DATABASEMANAGEMENTSERVICE']._serialized_end=862
# @@protoc_insertion_point(module_scope)
